/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CAL_H_RPCGEN
#define _CAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define OPER_OK 0
#define OPER_FAIL 1

struct result {
	int status;
	int result;
	int code_fail;
};
typedef struct result result;

struct values {
	int val1;
	int val2;
};
typedef struct values values;

#define CALPROG 0x30010001
#define CALVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUM 1
extern  result * sum_1(values *, CLIENT *);
extern  result * sum_1_svc(values *, struct svc_req *);
#define SUB 2
extern  result * sub_1(values *, CLIENT *);
extern  result * sub_1_svc(values *, struct svc_req *);
#define MUL 3
extern  result * mul_1(values *, CLIENT *);
extern  result * mul_1_svc(values *, struct svc_req *);
#define DIV 4
extern  result * div_1(values *, CLIENT *);
extern  result * div_1_svc(values *, struct svc_req *);
extern int calprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUM 1
extern  result * sum_1();
extern  result * sum_1_svc();
#define SUB 2
extern  result * sub_1();
extern  result * sub_1_svc();
#define MUL 3
extern  result * mul_1();
extern  result * mul_1_svc();
#define DIV 4
extern  result * div_1();
extern  result * div_1_svc();
extern int calprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_result (XDR *, result*);
extern  bool_t xdr_values (XDR *, values*);

#else /* K&R C */
extern bool_t xdr_result ();
extern bool_t xdr_values ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CAL_H_RPCGEN */
