/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cal.h"

bool_t
xdr_result (XDR *xdrs, result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->code_fail))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_values (XDR *xdrs, values *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->val1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->val2))
		 return FALSE;
	return TRUE;
}
