/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cal.h"


void
calprog_1(char *host)
{
	CLIENT *clnt;
	result  *result_1;
	values  sum_1_arg;
	result  *result_2;
	values  sub_1_arg;
	result  *result_3;
	values  mul_1_arg;
	result  *result_4;
	values  div_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALPROG, CALVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sum_1(&sum_1_arg, clnt);
	if (result_1 == (result *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = sub_1(&sub_1_arg, clnt);
	if (result_2 == (result *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = mul_1(&mul_1_arg, clnt);
	if (result_3 == (result *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = div_1(&div_1_arg, clnt);
	if (result_4 == (result *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calprog_1 (host);
exit (0);
}
