/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cal.h"

result *
sum_1_svc(values *argp, struct svc_req *rqstp)
{
	static result  result;

	/*
	 * insert server code here
	 */
	result.status = OPER_OK;
	result.code_fail = 0;
	result.result = argp->val1 + argp->val2;
	return &result;
}

result *
sub_1_svc(values *argp, struct svc_req *rqstp)
{
	static result  result;

	/*
	 * insert server code here
	 */

	return &result;
}

result *
mul_1_svc(values *argp, struct svc_req *rqstp)
{
	static result  result;

	/*
	 * insert server code here
	 */

	return &result;
}

result *
div_1_svc(values *argp, struct svc_req *rqstp)
{
	static result  result;

	/*
	 * insert server code here
	 */

	return &result;
}
