/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cal.h"

result *
sum_1_svc(values *argp, struct svc_req *rqstp)
{
	static result  result;

	/*
	 * insert server code here
	 */

	return &result;
}

result *
sub_1_svc(values *argp, struct svc_req *rqstp)
{
	static result  result;

	/*
	 * insert server code here
	 */

	return &result;
}

result *
mul_1_svc(values *argp, struct svc_req *rqstp)
{
	static result  result;

	/*
	 * insert server code here
	 */

	return &result;
}

result *
div_1_svc(values *argp, struct svc_req *rqstp)
{
	static result  result;

	/*
	 * insert server code here
	 */

	return &result;
}
