LDFLAGS=-lncurses

TARGETS=screensize stdscrsize corners center whereami

all: $(TARGETS)

# unicode: unicode.o
# 	$(CC) -o $@ $< -lncursesw

# ustring: ustring.o
# 	$(CC) -o $@ $< -lncursesw

clean:
	rm -f $(TARGETS)
	rm -f *.o
	rm -f *.*~ *~

