/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COMPILERJAVA_H_RPCGEN
#define _COMPILERJAVA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define OPER_OK 0
#define OPER_FAIL 1

struct result {
	int status;
};
typedef struct result result;

struct values {
	char path[256];
};
typedef struct values values;

#define COMPILERPROG 0x30010002
#define COMPILERVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define COMPILE 1
extern  result * compile_1(values *, CLIENT *);
extern  result * compile_1_svc(values *, struct svc_req *);
extern int compilerprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define COMPILE 1
extern  result * compile_1();
extern  result * compile_1_svc();
extern int compilerprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_result (XDR *, result*);
extern  bool_t xdr_values (XDR *, values*);

#else /* K&R C */
extern bool_t xdr_result ();
extern bool_t xdr_values ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COMPILERJAVA_H_RPCGEN */
