/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "compilerJava.h"
#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>

result *
compile_1_svc(values *argp, struct svc_req *rqstp)
{
	static result  result;
	pid_t childPid;
	/*
	 * insert server code here
	 */
	
	if ((childPid = fork()) == 0) {
	  execl("/opt/java/bin/javac", "javac", "/home/fcardona/tmp/HelloWorld.java", NULL);
	}
	else {
	  waitpid(childPid, &result.status, 0);
	}
	return &result;
}
