/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc2.h"

resultado *
sumar_1_svc(long val1, long val2,  struct svc_req *rqstp)
{
	static resultado  result;

	/*
	 * insert server code here
	 */

	

	return &result;
}
