/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc2.h"


void
calprog_1(char *host)
{
	CLIENT *clnt;
	resultado  *result_1;
	long sumar_1_val1 = 2;
	long sumar_1_val2 = 10;

#ifndef	DEBUG
	clnt = clnt_create (host, CALPROG, CALVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sumar_1(sumar_1_val1, sumar_1_val2, clnt);
	if (result_1 == (resultado *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calprog_1 (host);
exit (0);
}
