/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "int1.h"


void
int1_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	int  guardar_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, INT1, VERSIONINT1, "udp");
       
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	guardar_1_arg = 1000;

	result_1 = guardar_1(&guardar_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int1_1 (host);
exit (0);
}
