/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "int1.h"
#include "servidor.h"

void *
guardar_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;

	variable = *argp;
	/*
	 * insert server code here
	 */

	return (void *) &result;
}
