/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INT1_H_RPCGEN
#define _INT1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define INT1 0x3000FFF1
#define VERSIONINT1 1

#if defined(__STDC__) || defined(__cplusplus)
#define guardar 1
extern  void * guardar_1(int *, CLIENT *);
extern  void * guardar_1_svc(int *, struct svc_req *);
extern int int1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);
extern void int1_1d(struct svc_req *, register SVCXPRT *);
#else /* K&R C */
#define guardar 1
extern  void * guardar_1();
extern  void * guardar_1_svc();
extern int int1_1_freeresult ();
extern void int1_1d();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INT1_H_RPCGEN */
