/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INT2_H_RPCGEN
#define _INT2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define INT2 0x3000FFF2
#define VERSIONINT2 1

#if defined(__STDC__) || defined(__cplusplus)
#define obtener 1
extern  int * obtener_1(void *, CLIENT *);
extern  int * obtener_1_svc(void *, struct svc_req *);
extern int int2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);
extern void int2_1d(struct svc_req *, register SVCXPRT *);
#else /* K&R C */
#define obtener 1
extern  int * obtener_1();
extern  int * obtener_1_svc();
extern int int2_1_freeresult ();
extern void int2_1d();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INT2_H_RPCGEN */
