/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "int2.h"
#include "servidor.h"

int *
obtener_1_svc(void *argp, struct svc_req *rqstp)
{

	return &variable;
}
