/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rusers.h"
/*
 * Find out about remote users
 */

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
rusersproc_num_3(void *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RUSERSPROC_NUM,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

utmp_array *
rusersproc_names_3(void *argp, CLIENT *clnt)
{
	static utmp_array clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RUSERSPROC_NAMES,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_utmp_array, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

utmp_array *
rusersproc_allnames_3(void *argp, CLIENT *clnt)
{
	static utmp_array clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RUSERSPROC_ALLNAMES,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_utmp_array, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
